42-mighty-devs/42-ascension

- backend/jwt/exceptions/CustomException.py
- backend/jwt/jwtapp/decorators.py
- backend/jwt/jwtapp/utils.py
- backend/jwt/jwtapp/views.py
- backend/jwt/myjwt/middleware.py
- backend/jwt/myjwt/settings.py
- backend/jwt/run_server.sh
`Content-Type: application/json`으로 보냈을 때에 데이터 파싱을 하여 응답합니다.
다른 헤더 타입은 받지 않습니다.
> fix: parsing post json data

- backend/Makefile
- backend/auth/README.md
- backend/auth/authapp/urls.py
- backend/auth/authapp/views.py
- backend/auth/run_server.sh
- backend/docker-compose.yml
- backend/game/run_server.sh
- backend/jwt/jwtapp/utils.py
- backend/jwt/run_server.sh
- backend/nginx/nginx.conf
- backend/twofa/Dockerfile
- backend/twofa/run_server.sh
- backend/websocket/run_server.sh
- 도커가 처음 켜지면 DB 관련 migrate 불가 에러가 발생하는 문제를 수정하였습니다.
- `.mjs` 파일을 로드할 때, 그리고 새로고침 시 캐시가 사라지지 않는 현상을 수정하였습니다. 테스트를 위해서 수정하였습니다.
- `/mock` 경로의 명세사항을 일부 수정하였습니다.
> feat: docker error fix

- frontend/main.js
- frontend/modules/authentication/ftOauth.mjs
- frontend/modules/authentication/globalConstants.mjs
- frontend/modules/authentication/jwt.mjs
- frontend/modules/authentication/logout.mjs
- frontend/modules/authentication/twoFA.mjs
- frontend/modules/page/error.mjs
- frontend/modules/page/gameQueue.mjs
- frontend/modules/socketManager.mjs
1. fetch의 경로가 nginx 서버를 가리키도록 수정
2. quitQueue 버튼이 socket disconnect를 하지 않았던 문제 수정
3. 백엔드에서의 엔드 포인트 변경사항을 반영
- 1. /auth/ -> /api/auth/
- 2. /2fa/ -> /2fa/new/
> chore: 아래의 항목들을 작업

- backend/auth/auth/settings.py
- backend/docker-compose.yml
- backend/game/game/settings.py
- backend/game/gameapp/envs.py
- backend/game/gameapp/sio.py
- backend/jwt/myjwt/settings.py
- backend/nginx/nginx.conf
- backend/twofa/twofa/settings.py
- backend/user/server/config/settings.py
- backend/websocket/websocket/envs.py
- backend/websocket/websocket/settings.py
- backend/websocket/websocket/sio.py
외부에서 접근하기 위해서 cors_allowed_origins 옵션을 추가
> feat: 정상적으로 외부 컴퓨터에서 접속할 수 있도록 구현

- frontend/main.js
- frontend/modules/authentication/ftOauth.mjs
- frontend/modules/authentication/globalConstants.mjs
- frontend/modules/authentication/jwt.mjs
- frontend/modules/authentication/logout.mjs
- frontend/modules/authentication/twoFA.mjs
- frontend/modules/page/editProfile.mjs
- frontend/modules/page/gameQueue.mjs
- frontend/modules/page/gameQueueCreation.mjs
- frontend/modules/page/gamelobby.mjs
- frontend/modules/page/lowRankElements.mjs
- frontend/modules/page/manager.mjs
- frontend/modules/page/my.mjs
- frontend/modules/page/pong.mjs
- frontend/modules/page/tournament.mjs
- frontend/modules/socketManager.mjs
myPage와 editProfilePage가 백엔드에 요청을 날려 사용자 정보를 불러오도록, 그리고 사용자 정보를 수정할 수 있도록 구현했습니다. 다만 다음의 사항들을 추가로 구현해야 합니다.
1. myPage에서 사용자 정보를 가져올 때 쿼리문으로 user_name을 전달해야 하는데, 프론트엔드의 입장에서 자기 자신의 user_name을 알 수 없기 때문에 정상적으로 사용자 정보를 가져올 수 없습니다. 이 부분은 백엔드에서 user_named을 보내지 않으면 기본으로 자기 자신의 사용자 정보를 보내는 식으로 수정하기로 하였습니다. 백엔드에서 수정이 끝나면 프론트에서 마저 구현할 예정입니다.
2. editProfilePage에서 이미지 파일을 전송하는 것까지는 되는데, 그렇게 전송한 파일을 다시 불러오는 데에는 아직 문제가 있습니다. 이 문제는 추후 추가적으로 수정할 예정입니다.
3. jwt 토큰이 expired된 경우에 백엔드에서 해당하는 응답을 보내주지 않아서 jwt 토큰이 만료되면 지금 당장은 프론트가 바보가 됩니다. 이 부분도 백엔드에서 수정이 끝나면 추가로 작업할 예정입니다.
> Frontend/feat/add game myProfile EditProfile

- frontend/main.js
- frontend/modules/authentication/ftOauth.mjs
- frontend/modules/authentication/globalConstants.mjs
- frontend/modules/authentication/jwt.mjs
- frontend/modules/authentication/logout.mjs
- frontend/modules/authentication/twoFA.mjs
- frontend/modules/page/editProfile.mjs
- frontend/modules/page/my.mjs
- frontend/modules/page/twoFA.mjs
- 수정
1. async 함수에 await 키워드를 붙이지 않았던 부분을 수정
2. myPage, editPage에서 jwt expired일 때 토큰을 refresh하도록 수정
- 갱신
1. 2fa 인증 시 이전에 인증한 이력이 있을 경우 QrCode 없이 이전의 인증 코드로 인증할 수 있도록 수정
> feat: 다음의 사항들을 수정 및 갱신

- game/client/animation.js
- game/client/client.js
- game/client/gameOver.js
- game/client/geometrySetup.js
- game/client/index.html
- game/client/sceneSetup.js
- game/client/scoreboard.js
1. 카메라 위치 변경 (좀 더 경기장이 채워지도록 변경)
2. 스코어보드 최적화 및 설정 변경 (이제 폰트를 계속 로드하지 않고, 하나의 스코어보드만 렌더링합니다.)
3. 렌더러 설정 변경 (콘솔 에러 메시지)
> 클라이언트 코드 리팩토링

- frontend/game/animation.js
- frontend/game/client.js
- frontend/game/gameOver.js
- frontend/index.html
- frontend/main.js
- frontend/modules/authentication/jwt.mjs
- frontend/modules/page/aiMatch.mjs
- frontend/modules/page/editProfile.mjs
- frontend/modules/page/friend.mjs
- frontend/modules/page/gameQueue.mjs
- frontend/modules/page/gamelobby.mjs
- frontend/modules/page/login.mjs
- frontend/modules/page/manager.mjs
- frontend/modules/page/my.mjs
- frontend/modules/page/pong.mjs
- frontend/modules/page/tournament.mjs
- frontend/modules/page/twoFA.mjs
- frontend/pageDesign.css
그 외 자잘한 리팩토링을 조금 했습니다.
앞으로 할 일들
1. 게임 플레이 중 뒤로 가기 했을 때 socket이 disconnect 되도록 해야함
2. ai Match에 관련된 endpoint를 받으면 바로 작업해야 함
3. socket disconnect 되는 이슈 해결해야 함
> feat: friend 페이지 추가

- frontend/main.js
- frontend/modules/authentication/twoFA.mjs
- frontend/modules/page/editProfile.mjs
- frontend/modules/page/friend.mjs
- frontend/modules/page/gamelobby.mjs
- frontend/modules/page/my.mjs
- frontend/modules/socketManager.mjs
refresh 토큰이 만료되었을 때 로그아웃하지 않던 문제 수정
> fix: 다음의 사항을 수정

- frontend/index.html
- frontend/main.js
- frontend/modules/page/friend.mjs
- frontend/pageDesign.css
1. ctrl +로 페이지 요소가 화면 밖을 빠져나갈 때 스크롤이 적용되도록 함
2. 뒤로 가기를 통해 friend 페이지로 접근했을 때 가장 최근에 조회했던 friend의 정보가 뜨도록 함
> feat: 다음의 사항들을 구현

- backend/game/game/urls.py
- backend/game/game/wsgi.py
- backend/game/gameapp/urls.py
- backend/game/gameapp/views.py
- backend/game/gameapp/wsgi_utils.py
- backend/nginx/nginx.conf
> feat: make post ai match pulic endpoint

- backend/user/server/user/views.py
/user/dashboard로 GET 요청을 받을때, 데이터가 없을 경우 반환할 디폴드 값을 만들었습니다.
> fix: dashboard-views.py

- backend/auth/auth/middleware.py
- backend/auth/authapp/requests.py
- backend/auth/authapp/views.py
- backend/game/game/decorators.py
- backend/game/game/middleware.py
- backend/game/game/wsgi.py
- backend/game/gameapp/match_objects/match.py
- backend/game/gameapp/match_objects/process.py
- backend/game/gameapp/requests.py
- backend/game/gameapp/utils.py
- backend/game/gameapp/views.py
- backend/game/gameapp/wsgi_utils.py
- backend/game_ai/ai/requests.py
- backend/game_ai/game_ai/middleware.py
- backend/jwt/jwtapp/requests.py
- backend/jwt/jwtapp/utils.py
- backend/jwt/myjwt/middleware.py
- backend/twofa/twofa/middleware.py
- backend/twofa/twofaapp/views.py
- backend/websocket/websocket/decorators.py
- backend/websocket/websocket/middleware.py
- backend/websocket/websocket/requests.py
- backend/websocket/websocket/sio.py
- backend/websocket/websocket/userdict.py
- backend/websocket/websocket/utils.py
- backend/websocket/websocket/wsgi.py
> feat: logging

- backend/game/gameapp/match_objects/match.py
- backend/game/gameapp/match_objects/process.py
- backend/game/gameapp/sio.py
- backend/game/gameapp/wsgi_utils.py
- backend/game/run_server.sh
- backend/game_ai/ai/views.py
> chore: 게임 백엔드를 어떻게든 돌리려는 이모저모

- frontend/modules/page/dashboard.mjs
- frontend/modules/page/gamelobby.mjs
- frontend/modules/page/manager.mjs
1. loginPage에서 앞으로가기 할 때 발생하는 에러 수정
2. ai Match 시 자동으로 room socket disconnect
3. dashboard에서 refresh 만료시 로그아웃
> fix: 다음의 사항들을 수정

- backend/game/gameapp/match_objects/match.py
- backend/websocket/websocket/userdict.py
- `opponent` 이벤트에 대해 새로운 `lastGame` 키에 마지막 게임일 경우 true, 아닐 경우 false를 넣어 반환합니다.
- 프론트엔드에서 활용하여 마지막 게임이면 나가는 버튼을 띄우는 용도로 사용하기 위해 추가하였습니다.
> feat: lastGame key when winner decided

- backend/auth/authapp/utils.py
- backend/docker-compose.yml
- backend/game/game/wsgi.py
- backend/game/gameapp/connect_utils.py
- backend/game/gameapp/db_utils.py
- backend/game/gameapp/match_objects/process.py
- backend/game/gameapp/match_objects/timeout.py
- backend/game/gameapp/match_objects/waiting.py
- backend/game/gameapp/utils.py
- backend/game/gameapp/views.py
- backend/game/gameapp/wsgi_utils.py
- backend/jwt/README.md
- backend/jwt/jwtapp/utils.py
- backend/jwt/jwtapp/views.py
- backend/twofa/twofaapp/models.py
- backend/twofa/twofaapp/views.py
- backend/websocket/exceptions/CustomException.py
- backend/websocket/websocket/userdict.py
- backend/websocket/websocket/wsgi.py
- 게임에서 내부 에러 발생할 경우 유저가 다시 들어오지 못하는 문제 수정
- `startGame` 이벤트 시 토큰을 다시 발급하도록 수정
- 각종 에러 시 비정상 종료하지 않도록 수정
- 사람이 다 들어오지 않았을 경우 대기하고, 다 들어올 경우 게임을 시작하도록 수정
> feat: game fix

- frontend/modules/authentication/ftOauth.mjs
- frontend/modules/authentication/globalConstants.mjs
> refactor: 서버 주소를 전역 상수로서 접근하게 함

- frontend/game/client.js
- frontend/game/gameOver.js
게임 종료 시
1. 패배 시 -> 나가기 버튼 고정
2. 게임 종료가 되지 않았을 때 opponent가 들어와도 팝업 띄우지 않도록 설정
TODO : 키 이벤트 분리 및 추상화
> 게임 종료 상태를 승패에 따른 분리

- backend/nginx/nginx.conf
- backend/user/server/config/settings.py
> fix: fix nginx.conf to allow 10M file upload

- frontend/modules/authentication/logout.mjs
- frontend/modules/page/editProfile.mjs
- frontend/modules/socketManager.mjs
1. room socket 연결 시 서버로부터 자신의 사용자 이름을 받아오도록 변경
2. editProfile 페이지에서 프로필 변경 성공 시 메세지 출력하도록 변경
> feat: 다음의 사항을 구현

- frontend/modules/page/dashboard.mjs
1. fetch 를 했을때, 에러가 나면 return이 안 되던 것을 해결했습니다.
2. 에러가 났을 경우 undefined를 리턴했을 경우의 처리를 추가하였습니다.
> fix: return문 추가, undefined 추가

- frontend/modules/page/dashboard.mjs
> fix: average 문구 변경

- backend/Makefile
- backend/docker-compose.yml
- backend/game/game/decorators.py
- backend/game/gameapp/connect_utils.py
- backend/game/gameapp/db_utils.py
- backend/game/gameapp/match_objects/match.py
- backend/game/gameapp/match_objects/matchdict.py
- backend/game/gameapp/match_objects/matchuser.py
- backend/game/gameapp/match_objects/process.py
- backend/game/gameapp/sio.py
- backend/game/gameapp/views.py
- backend/game/gameapp/wsgi_utils.py
- backend/game_ai/ai/views.py
- backend/twofa/twofaapp/envs.py
- backend/twofa/twofaapp/migrations/0004_userinfo_twofa_stored.py
- backend/twofa/twofaapp/views.py
- backend/websocket/websocket/room.py
- backend/websocket/websocket/wsgi.py
- frontend/modules/socketManager.mjs
- `paddleMove`, `updateBall` 등 반복되는 이벤트일 시 로깅 최소화
- `match_dict`에 lock으로 동시성 관리를 하지 않아 생기는 문제 해결
- AI에게 `updateBall` 이벤트 명세가 다른 점 반영하지 않은 문제 해결
- username을 반환하는 weboscket 이벤트 추가
- twofa otp 인증을 일정 시간 지나도 유효하도록 변경
- 데드락 문제 해결
> fix: bug fixes

- frontend/game/animation.js
- frontend/game/client.js
- frontend/game/scoreboard.js
> 점수판 아래에 상대편 이름 추가 및 키 이벤트 초기화

- backend/Makefile
- backend/game/gameapp/connect_utils.py
- backend/game/gameapp/match_objects/match.py
- backend/game/gameapp/match_objects/matchdict.py
- backend/game/gameapp/match_objects/matchuser.py
- backend/game/gameapp/match_objects/process.py
- backend/game/gameapp/utils.py
- backend/game/gameapp/wsgi_utils.py
- backend/websocket/websocket/userdict.py
- frontend/game/animation.js
- frontend/game/client.js
- frontend/modules/socketManager.mjs
- 백엔드 경기 안 되던 문제 수정
- 프론트엔드 소켓 관련 누수 수정
- 게임 패들 속도가 두 배이던 문제 수정
> hotfix: backend/frontend error fix

- frontend/game/animation.js
- frontend/game/client.js
- 게임에서 다음 게임으로 갈 경우 패들 속도가 두 배가 되던 현상을 수정하였습니다.
- 이벤트, 애니메이션 등 게임이 종료되어도 유지되던 현상을 수정하였습니다.
> fix: game paddle speed, delete events

- frontend/modules/authentication/twoFA.mjs
- frontend/modules/page/twoFA.mjs
> fix: otpName에 너무 긴 문자열을 주었을 때의 비정상 동작을 수정
